require("plugins.setup")
require("core.options")
require("core.keymaps")
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.nvim-tree")
require("plugins.mason")
require("plugins.gitsigns")
require("plugins.fuzzy_telescope")
require("plugins.nvim-cmp")
require("plugins.nvim-treesitter")
require("plugins.comment")
require("plugins.null-ls")
require("plugins.lsp.mason-lspconfig")

